#!/bin/bash

[ $USER == root ] || {
    echo "Run as sudo"
    exit 1
}

RBB_NAME=raspberry-blue-bridge 

# Configuration and virtual env will be in this dir
# Can ba changed with environment variable RBB_DIR
# If not set, use default
[ $RBB_DIR ] || RBB_DIR="/usr/local/etc/${RBB_NAME}"
VENV=$RBB_DIR/venv

# Other arguments handle by python program

[ -d $VENV ] || {
    echo "Set up venv $VENV"
    python3 -m venv $VENV
    source $VENV/bin/activate
    pip3 install -r $RBB_DIR/requirements.txt
}

$VENV/bin/python $RBB_DIR/rbb.py --dir $RBB_DIR $@
